- name: Install and update packages
  hosts: 134.122.36.252
  become: yes
  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure latest version of all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
