- name: Set up Prometheus
  hosts: all
  become: yes
  tasks:
    - name: Download Prometheus
      ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt
        remote_src: yes

    - name: Ensure Prometheus service is running
      ansible.builtin.systemd:
        name: prometheus
        enabled: yes
        state: started
